---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cadvisor
  namespace: monitoring
  labels:
    prometheus: main
spec:
  selector:
    matchLabels:
      name: cadvisor
  podMetricsEndpoints:
    - port: http
