---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: gmp-main
  namespace: gmp-monitoring
spec:
  version: v2.43.1 # Still necessary based on doc
  image: gke.gcr.io/prometheus-engine/prometheus:v2.43.1-gmp.0-gke.0
  serviceAccountName: my-gmp-prometheus
  serviceMonitorSelector:
    matchLabels:
      component: main
  podMonitorSelector:
    matchLabels:
      component: main
  serviceMonitorNamespaceSelector:
    matchLabels:
      monitoring: gmp-prometheus
  podMonitorNamespaceSelector:
    matchLabels:
      monitoring: gmp-prometheus
  # resources:
  #   requests:
  #     cpu: 500m
  #     memory: 2Gi
  #   limits:
  #     cpu: 500m
  #     memory: 2Gi
  replicas: 1
  logLevel: info
  logFormat: logfmt
  scrapeInterval: 15s
  securityContext:
    fsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
  # storage:
  #   volumeClaimTemplate:
  #     spec:
  #       resources:
  #         requests:
  #           storage: 20Gi
