---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: myapp
  namespace: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  # https://github.com/GoogleCloudPlatform/prometheus-engine/blob/v0.10.0/doc/api.md#scrapeendpoint
  endpoints:
    - port: prom-metrics
