---
apiVersion: v1
kind: Secret
metadata:
  namespace: gmp-monitoring
  name: grafana
type: Opaque
data:
  admin-user: "YWRtaW4=" # base64 encoded "admin"
  admin-password: "ZGV2b3BzMTIz" # base64 encoded "devops123"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: gmp-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
        runAsUser: 472
      containers:
        - name: grafana
          image: grafana/grafana:11.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: grafana
              containerPort: 3000
              protocol: TCP
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: grafana
                  key: admin-user
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana
                  key: admin-password
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 60
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: gmp-monitoring
  name: grafana
spec:
  type: ClusterIP
  ports:
    - name: service
      port: 3000
      protocol: TCP
  selector:
    app: grafana
