---
apiVersion: v1
kind: Secret
metadata:
  name: private-003
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:antonputra/private-003.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACA9X6rTtenCIYr7k8y+Hby/dbtBuThM1sQ1pRzENhJ8pgAAAJhTtVbPU7VW
    zwAAAAtzc2gtZWQyNTUxOQAAACA9X6rTtenCIYr7k8y+Hby/dbtBuThM1sQ1pRzENhJ8pg
    AAAECpp9XWkMktJY02Jtg1aATcH8XlRgWu4HVXMxjDXODfUj1fqtO16cIhivuTzL4dvL91
    u0G5OEzWxDWlHMQ2EnymAAAAFWFyZ29jZEBhbnRvbnB1dHJhLmNvbQ==
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "true"
