---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: cadvisor
  namespace: monitoring
  labels:
    prometheus: main
spec:
  selector:
    matchLabels:
      name: cadvisor
  endpoints:
    - port: http
