---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: myapp
  namespace: gmp-monitoring
  labels:
    component: main
spec:
  namespaceSelector:
    matchNames:
      - myapp
  selector:
    matchLabels:
      app: myapp
  podMetricsEndpoints:
    - port: prom-metrics
