---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: 424432388155.dkr.ecr.us-east-2.amazonaws.com/myapp-003-amd64:0.x
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:antonputra/private-003.git
    targetRevision: main
    # location of the helm chart
    path: charts/myapp
    helm:
      parameters:
        - name: "replicaCount"
          value: "2"
  destination:
    server: https://kubernetes.default.svc
    # namespace to deploy helm chart
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
